# pid must be in a directory writable by non-root user
pid /tmp/nginx.pid;

events {}

http {
    server {
        # non-privileged port — required for non-root user
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}