server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # New line added
    add_header X-Demo-Header "live-reload-works";

    location / {
        try_files $uri $uri/ =404;
    }
}
